#include <iostream>
#include <string>

using namespace std;

int main(){
	string a;
	
	cout << "Enter your word:";
	cin >> a;
	
	if (a == "ACTUATOR"){
		cout <<"AN END DEVICE OF A CONTROL SYSTEM, THAT MANIPULATES A PHYSICAL VARIABLE SUCH AS A VALVE OPENING OR POSITION OF A MACHINE PART.";
	}else if (a == "ANTENNA"){
		cout <<"A STRUCTURE WHICH CONVERTS BETWEEN ELECTROMAGNETIC WAVES IN SPACE AND CURRENTS IN A CONDUCTOR.";
	}else if (a == "BANDWIDTH"){
		cout <<"THE RANGE OF FREQUENCIES OVER WHICH A SYSTEM GENERATES OR USES SIGNIFICANT SIGNAL POWER.";
	}else if (a == "BUSHING"){
		cout <<"AN ELECTRICAL FITTING USED TO CONNECT EXTERNAL CONDUCTORS TO THE INTERIOR OF APPARATUS";
	}else if (a == "CAPACITOR"){
		cout <<"AN ELECTRICAL COMPONENT THAT STORES ENERGY IN AN ELECTRIC FIELD.";
	}else if (a == "CATHODE"){
		cout <<"THE TERMINAL OF AN ELECTROCHEMICAL OR ELECTRONIC DEVICE FROM WHICH CONVENTIONAL CURRENT EXITS THE DEVICE.";
	}else if (a == "DETECTOR"){
		cout <<"A CIRCUIT THAT DEMODULATES A RADIO SIGNAL TO RECOVER INFORMATION.";
	}else if (a == "ELECTRONICS"){
		cout <<"THE STUDY OF THE FLOW OF ELECTRONS THROUGH A VACUUM, GASES OR SEMICONDUCTORS.";
	}else if (a == "FEEDBACK"){
		cout <<"A SYSTEM THAT SAMPLES PART OF ITS OUTPUT AND ADDS THAT TO ITS INPUT; FEEDBACK MAY BE POSTIVE OR NEGATIVE.";
	}else if (a == "FIRMWARE"){
		cout <<"A FORM OF MICRODE OR PROGRAM EMBEDDED INTO HARDWARE DEVICES TO HELP THEM OPERATE EFFECTIVELY.";
	}else if (a == "GENERATOR"){
		cout <<"A MACHINE THAT CHANGES MECHANICAL OR CHEMICAL ENERGY INTO ELECTRICAL ENERGY.";
	}else if (a == "HEATSINK"){
		cout <<"A STRUCTURE INTENDED TO DISSIPATE HEAT FROM AN ACTIVE DEVICE INTO THE AMBIENT ENVIRONMENT.";
	}else if (a == "INSULATOR"){
		cout <<"A SUBSTANCE THAT DOES NOT PERMIT EASY FLOW OF ELECTRICAL CURRENT; A FITTING INTENDED TO SUPPORT A CONDUCTOR.";
	}else if (a == "JITER"){
		cout <<"DEVIATION FROM THE TRUE PERIODICITY OF A PERIODIC SIGNAL.";
	}else if (a == "KLYSTRON"){
		cout <<"A TYPE OF MICROWAVE OSCILLATOR VACUUM TUBE. IT'S USED IN MANY APPLICATIONS, INCLUDING RADAR, SATELLITE COMMUNICATIONS, AND PARTICLE.";
	}else if (a == "BUSHING"){
		cout <<"AN ELECTRICAL FITTING USED TO CONNECT EXTERNAL CONDUCTORS TO THE INTERIOR OF APPARATUS";
	}else if (a == "LAN"){
		cout <<"LOCAL AREA NETWORK, AN INTERCONNECTION OF COMPUTERS OVER A BUILDING OR SMALL CAMPUS.";
	}else if (a == "MAGNETISM"){
		cout <<"THE CLASS OF NATURAL PHENOMENA RELATED TO MAGNETS AND MAGNETIC FIELDS.";
	}else if (a == "MP3"){
		cout <<"A STANDARD FOR ENCODING AUDIO IN DIGITAL FORM.";
	}else if (a == "NODE"){
		cout <<"A DEFINED POINT IN AN ELECTRICAL NETWORK, WITH SOME POTENTIAL RELATIVE TO A REFERENCE NODE AND WHERE CURRENTS CAN BE SUMMED.";
	}else if (a == "OPTICAL FIBER"){
		cout <<"A GLASS OR PLASTIC FIBER USED TO CONVEY SIGNALS TRANSMITTED BY VISIBLE LIGHT OR INFRARED RADIATION.";
	}else if (a == "PHOTOCELL"){
		cout <<"A LIGHT SENSOR THAT PRODUCES OR ALTERS A VOLTAGE WHEN LIGHT IS PRESENT.";
	}else if (a == "QUANTIZATION"){
		cout <<"ANALOG TO DIGITAL CONVERSION, CHANGING A CONTINUOUSLY VARYING ANALOG SIGNAL TO DISCRETE DIGITAL NUMBERS.";
	}else if (a == "RADAR"){
		cout <<"RADIO DETECTION AND RANGING, THE TECHNIQUES FOR OBESERVING THE SPEED AND POSITION OF OBJECTS BY REFLECTED RADIO WAVES.";
	}else if (a == "SOFTWARE"){
		cout <<"WRITTEN PROGRAMS OPERATING ON A COMPUTER SYSTEM.";
	}else if (a == "SATELLITE"){
		cout <<"A NATURAL OR ARTIFICIAL OBJECT THAT CIRCLES ANOTHER, BOUND ONLY BY GRAVITY.";
	}else if (a == "TELEGRAPH"){
		cout <<"A SYSTEM FOR TRANSMITTING TEXT MESSAGES, BY WIRE OR OTHER MEANS.";
	}else if (a == "TRANSFORMER"){
		cout <<"A STATIC ARRANGEMENT OF CONDUCTORS AND POSSIBLY MAGNETIC MATERIALS, THAT TRANSFERS ENERGY BY ELECTROMAGNETIC INDUCTION.";
	}else if (a == "ULTRASOUND"){
		cout <<"SOUND HAVING A FREQUENCY ABOVE THE RANGE OF NORMAL HUMAN HEARING. A PORTMANTEAU OF THE FORMER DESCRIPTION OF 'ULTRASONIC SOUND.";
	}else if (a == "VOLTMETER"){
		cout <<"AN INSTRUMENT FOR MEASURING POTENTIAL DIFFERENCE.";
	}else if (a == "WATT"){
		cout <<"A UNIT OF MEASUREMENT FOR POWER OR THE RATE OF ENERGY TRANSFER";
	}else{
		cout << "Try a different word";
	}
	return 0;
}